# Generated by Django 4.2.7 on 2023-11-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("IRR", "Irr"), ("IRT", "Irt")],
                        max_length=3,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Amount"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("OK", "Ok"), ("NOK", "Nok")],
                        max_length=3,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Authority ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Status Code"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ref ID"
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Card pan"
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="fee type"
                    ),
                ),
                (
                    "fee",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="fee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "abstractpayment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payment.abstractpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
            bases=("payment.abstractpayment",),
        ),
    ]
